# Generated by Django 4.2.11 on 2026-06-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_servicephoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('manual', 'Manual'), ('paid', 'Paid')], max_length=20)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_badge', to='services.serviceprofile')),
            ],
            options={
                'db_table': 'verified_badges',
            },
        ),
    ]
