# Generated by Django 4.2.11 on 2026-06-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0004_servicephoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swipe_status', models.CharField(choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('seen', 'Seen')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reset_at', models.DateTimeField(blank=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_history', to='accounts.telegramuser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_history', to='services.serviceprofile')),
            ],
            options={
                'db_table': 'swipe_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='swipe_customer_idx'), models.Index(fields=['service'], name='swipe_service_idx'), models.Index(fields=['reset_at'], name='swipe_reset_idx')],
            },
        ),
    ]
