# Generated by Django 4.2.11 on 2026-06-29 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegramuser_admin_tested_badge_telegramuser_city_and_more'),
        ('services', '0006_add_denial_log_and_penalty_count'),
        ('swipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_services', to='accounts.telegramuser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='services.serviceprofile')),
            ],
            options={
                'db_table': 'saved_service_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='savedservicerequest',
            constraint=models.UniqueConstraint(fields=('customer', 'service'), name='unique_saved_service_per_customer'),
        ),
    ]
