# Generated by Django 4.2.11 on 2026-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique service category name.', max_length=120, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Controls whether this category is available for marketplace use.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='svc_category_name_idx'), models.Index(fields=['active'], name='svc_category_active_idx')],
            },
        ),
    ]
