# Generated by Django 4.2.11 on 2026-06-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Public service title.', max_length=180)),
                ('description', models.TextField(help_text='Public service description.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Provider latitude when GPS location is available.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Provider longitude when GPS location is available.', max_digits=9, null=True)),
                ('city_text', models.CharField(blank=True, help_text='Manual city text when GPS is not provided.', max_length=150)),
                ('location_source', models.CharField(choices=[('gps', 'GPS'), ('city_text', 'City Text'), ('both', 'Both')], db_index=True, default='city_text', max_length=20)),
                ('visibility_status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], db_index=True, default='on', max_length=10)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin Telegram user who approved this service profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_service_profiles', to='accounts.telegramuser')),
                ('category', models.ForeignKey(help_text='Service category selected by the provider.', on_delete=django.db.models.deletion.PROTECT, related_name='service_profiles', to='services.servicecategory')),
                ('provider', models.OneToOneField(help_text='Provider who owns this service profile. One provider can have only one service profile.', on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to='accounts.telegramuser')),
            ],
            options={
                'verbose_name': 'Service Profile',
                'verbose_name_plural': 'Service Profiles',
                'db_table': 'service_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['approval_status'], name='svc_profile_approval_idx'), models.Index(fields=['visibility_status'], name='svc_profile_visible_idx'), models.Index(fields=['location_source'], name='svc_profile_location_idx'), models.Index(fields=['city_text'], name='svc_profile_city_idx'), models.Index(fields=['created_at'], name='svc_profile_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceprofile',
            constraint=models.UniqueConstraint(fields=('provider',), name='unique_service_profile_per_provider'),
        ),
    ]
