# Generated by Django 4.2.11 on 2026-06-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0002_serviceprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_service_profiles', to='accounts.telegramuser'),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_profiles', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='city_text',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to='accounts.telegramuser'),
        ),
        migrations.AlterField(
            model_name='serviceprofile',
            name='title',
            field=models.CharField(max_length=180),
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('half_day', 'Half Day'), ('full_day', 'Full Day'), ('night', 'Night')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price amount in ETB.', max_digits=10)),
                ('service', models.ForeignKey(help_text='Service profile this price belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.serviceprofile')),
            ],
            options={
                'verbose_name': 'Service Price',
                'verbose_name_plural': 'Service Prices',
                'db_table': 'service_prices',
                'ordering': ['service', 'price_type'],
                'indexes': [models.Index(fields=['service'], name='svc_price_service_idx'), models.Index(fields=['price_type'], name='svc_price_type_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.UniqueConstraint(fields=('service', 'price_type'), name='unique_price_type_per_service'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='service_price_amount_positive'),
        ),
    ]
