# Generated by Django 4.2.11 on 2026-06-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_serviceprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_file_id', models.CharField(max_length=512)),
                ('order_index', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.serviceprofile')),
            ],
            options={
                'db_table': 'service_photos',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicephoto',
            constraint=models.UniqueConstraint(fields=('service', 'order_index'), name='unique_photo_order_per_service'),
        ),
    ]
