# Generated by Django 4.2.11 on 2026-06-29 15:59

from django.db import migrations, models


def seed_city_locations(apps, schema_editor):
    CityLocation = apps.get_model('services', 'CityLocation')
    
    # Addis Ababa
    CityLocation.objects.update_or_create(
        name="Addis Ababa",
        defaults={
            "top_left_x": 38.623100,
            "top_left_y": 9.123600,
            "top_right_x": 38.939480,
            "top_right_y": 9.123600,
            "bottom_right_x": 38.939480,
            "bottom_right_y": 8.850684,
            "bottom_left_x": 38.623100,
            "bottom_left_y": 8.850684,
        }
    )
    
    # Adama
    CityLocation.objects.update_or_create(
        name="Adama",
        defaults={
            "top_left_x": 39.207900,
            "top_left_y": 8.597673,
            "top_right_x": 39.326240,
            "top_right_y": 8.597673,
            "bottom_right_x": 39.326240,
            "bottom_right_y": 8.461662,
            "bottom_left_x": 39.207900,
            "bottom_left_y": 8.461662,
        }
    )
    
    # Hawassa
    CityLocation.objects.update_or_create(
        name="Hawassa",
        defaults={
            "top_left_x": 38.444050,
            "top_left_y": 7.113437,
            "top_right_x": 38.536640,
            "top_right_y": 7.113437,
            "bottom_right_x": 38.536640,
            "bottom_right_y": 7.003403,
            "bottom_left_x": 38.444050,
            "bottom_left_y": 7.003403,
        }
    )
    
    # Mekele
    CityLocation.objects.update_or_create(
        name="Mekele",
        defaults={
            "top_left_x": 39.423690,
            "top_left_y": 13.582720,
            "top_right_x": 39.523710,
            "top_right_y": 13.582720,
            "bottom_right_x": 39.523710,
            "bottom_right_y": 13.457730,
            "bottom_left_x": 39.423690,
            "bottom_left_y": 13.457730,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicephoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Unique city name.', max_length=120, unique=True)),
                ('top_left_x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('top_left_y', models.DecimalField(decimal_places=6, max_digits=9)),
                ('top_right_x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('top_right_y', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bottom_right_x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bottom_right_y', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bottom_left_x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bottom_left_y', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'City Location',
                'verbose_name_plural': 'City Locations',
                'db_table': 'city_locations',
            },
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='admin_forced_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin-only: hide this provider from all discovery regardless of visibility status.'),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='denial_count',
            field=models.PositiveIntegerField(default=0, help_text='Total contact request denials (including timeouts) by this provider.'),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='likes_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total swipe-likes received on this service profile.'),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='location_update_requested_at',
            field=models.DateTimeField(blank=True, help_text='When admin last asked this provider to update their location.', null=True),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='penalty_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Penalty expiry time. Provider is hidden from discovery until this time.', null=True),
        ),
        migrations.AddField(
            model_name='serviceprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin-provided explanation when this service registration is rejected.'),
        ),
        migrations.RunPython(seed_city_locations),
    ]
