# Generated by Django 4.2.11 on 2026-06-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_contactrequest_service_alter_contactrequest_status_and_more'),
        ('services', '0005_citylocation_serviceprofile_admin_forced_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='penalty_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times a penalty has been applied to this service.'),
        ),
        migrations.CreateModel(
            name='ProviderDenialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('manual_reject', 'Manual Reject'), ('timeout', 'Timeout (24h)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contact_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.contactrequest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denial_logs', to='services.serviceprofile')),
            ],
            options={
                'db_table': 'provider_denial_logs',
                'indexes': [models.Index(fields=['service'], name='pdl_service_idx'), models.Index(fields=['created_at'], name='pdl_created_idx')],
            },
        ),
    ]
