# Generated by Django 4.2.11 on 2026-06-29 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_add_denial_log_and_penalty_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_file_id', models.CharField(max_length=512)),
                ('order_index', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_change_requests', to='services.serviceprofile')),
            ],
            options={
                'db_table': 'photo_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
