# Generated by Django 4.2.11 on 2026-06-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_photochangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='prior_penalty_count',
            field=models.PositiveIntegerField(default=0, help_text='Tracks number of penalties applied (prior to latest).'),
        ),
    ]
