# Generated by Django 4.2.11 on 2026-07-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_default_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicephoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_photos/'),
        ),
    ]
