# Generated by Django 4.2.11 on 2026-07-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_servicephoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofile',
            name='acceptance_count',
            field=models.PositiveIntegerField(default=0, help_text='Total contact requests approved (admin or auto) for this provider.'),
        ),
    ]
