# Generated by Django 4.2.11 on 2026-06-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, help_text='Unique Telegram user ID.', unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username without @ when available.', max_length=150)),
                ('first_name', models.CharField(blank=True, help_text='Telegram first name when available.', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Telegram last name when available.', max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number shared through Telegram contact flow when available.', max_length=32)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider'), ('admin', 'Admin'), ('both', 'Both')], db_index=True, default='customer', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_banned', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
                'db_table': 'telegram_users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_id'], name='tg_user_telegram_id_idx'), models.Index(fields=['role'], name='tg_user_role_idx'), models.Index(fields=['is_banned'], name='tg_user_banned_idx'), models.Index(fields=['is_verified'], name='tg_user_verified_idx')],
            },
        ),
    ]
