# Generated by Django 4.2.11 on 2026-06-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='secondary_phone_number',
            field=models.CharField(blank=True, help_text='Optional secondary phone number for contact sharing.', max_length=32, null=True),
        ),
    ]
