# Generated by Django 4.2.11 on 2026-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegramuser_secondary_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='policy_accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the user passed the Telegram policy verification test.', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='policy_blocked_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Temporary block window after a failed policy verification.', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='policy_failed_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of failed policy verification attempts.'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='policy_version',
            field=models.CharField(blank=True, help_text='Policy version accepted by the Telegram user.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['policy_accepted_at'], name='tg_user_policy_idx'),
        ),
    ]
