# Generated by Django 4.2.11 on 2026-06-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramuser_policy_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='admin_tested_badge',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin has personally tested and verified this provider.'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='city',
            field=models.CharField(blank=True, help_text='City matched from GPS location coordinates.', max_length=150),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='customer_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Customer GPS latitude for proximity matching.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='customer_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When customer last submitted their GPS location.', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='customer_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Customer GPS longitude for proximity matching.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_interaction_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Timestamp of user's last interaction with the bot or mini app.", null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='likes_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total number of swipe-likes received by this provider.'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['customer_latitude', 'customer_longitude'], name='tg_user_cust_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['last_interaction_at'], name='tg_user_last_interact_idx'),
        ),
    ]
