# Generated by Django 4.2.11 on 2026-06-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotRegistrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('state', models.CharField(choices=[('select_role', 'Select Role'), ('provider_phone', 'Provider Phone'), ('secondary_phone', 'Secondary Phone'), ('category', 'Category'), ('title', 'Title'), ('description', 'Description'), ('location', 'Location'), ('prices', 'Prices'), ('photos', 'Photos'), ('submit', 'Submit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='select_role', max_length=40)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bot_registration_sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
