# Generated by Django 4.2.11 on 2026-06-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botregistrationsession',
            name='state',
            field=models.CharField(choices=[('select_role', 'Select Role'), ('provider_phone', 'Provider Phone'), ('secondary_phone', 'Secondary Phone'), ('category', 'Category'), ('title', 'Title'), ('description', 'Description'), ('location', 'Location'), ('prices', 'Prices'), ('photos', 'Photos'), ('submit', 'Submit'), ('policy', 'Policy'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='select_role', max_length=40),
        ),
    ]
