# Generated by Django 4.2.11 on 2026-06-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_botregistrationsession_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='botregistrationsession',
            name='city',
            field=models.CharField(blank=True, help_text='Temporary city field during registration.', max_length=150),
        ),
    ]
