# Generated by Django 4.2.11 on 2026-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botregistrationsession_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botregistrationsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
