# Generated by Django 4.2.11 on 2026-06-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_requests', models.BooleanField(default=False)),
                ('reset_days', models.PositiveIntegerField(default=6)),
                ('default_radius', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_settings',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto Approved')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contact_requests', to='accounts.telegramuser')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests_sent', to='accounts.telegramuser')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests_received', to='accounts.telegramuser')),
            ],
            options={
                'db_table': 'contact_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='contact_customer_idx'), models.Index(fields=['provider'], name='contact_provider_idx'), models.Index(fields=['status'], name='contact_status_idx')],
            },
        ),
    ]
