# Generated by Django 4.2.11 on 2026-06-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicephoto_and_more'),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='services.serviceprofile'),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('provider_pending', 'Provider Pending'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('provider_rejected', 'Provider Rejected'), ('auto_approved', 'Auto Approved')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['service'], name='contact_service_idx'),
        ),
    ]
