# Generated by Django 4.2.11 on 2026-06-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_contactrequest_service_alter_contactrequest_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['provider', 'status'], name='contact_provider_status_idx'),
        ),
    ]
