# Generated by Django 4.2.11 on 2026-06-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_add_provider_status_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('no_reason', models.CharField(blank=True, choices=[('price_change', 'Change in price'), ('transport_cost', 'Transport cost > 1000 ETB'), ('advance_too_high', 'Advance payment > 30%'), ('provider_not_responding', 'Provider not responding'), ('provider_no_show', "Provider didn't come after advance"), ('personal', "I don't like her")], max_length=50)),
                ('contact_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='approvals.contactrequest')),
            ],
            options={
                'db_table': 'customer_surveys',
            },
        ),
    ]
